### ISSUE TITLE
[API] Move runtime objects related configuration out of spec.Application 

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#178]
By idea, spec.Application section is for configuration Backstage Application container (app-configs, extra files, env vars...) and it is quite confusing to see configuration of workload k8s objects (such as replicas, network, image etc) here as well.

Proposal is to:
- move backstage runtime configuration (image, replicas, image-pull secrets) on top level
- move route to new Network section

So CR.spec would look like this:
```
spec:
  image: my-img
  imagePullSecrets: []
  replicas: 2
  application:
    appConfig: {}
    extraFiles: {}
    extraEnvs: {}
    dynamicPluginsConfigMapName: my-dp-cm
  database:
    enableLocalDb: true
  network:
   route: {}
```
