### ISSUE TITLE
Do not use SubPath for mounting ConfigMap and Secret configuration files if Key not specified 

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#179]
Problems:
- For the time we extensively use mounting CM/Secret configuration files using SubPath to not to cause overwriting the whole directory. The problem of this approach is that mounted configuration file is not changed when respective  CM/Secret data changed (see: https://github.com/janus-idp/operator/issues/125 ). 

Proposals:
- Not to use SubPath for mounting CM/Secret if Key is not pointed and mount Data files to dedicated directory, taking from CM/Secret name or (better UX but requires slightly API change) add another field or move mountPath: to the configuration spec, per CM/Secret 

Example:

Incompatible with current:
```
spec:
  application:
    extraFiles:
      configMaps:
        - name: 
           mountPath: /tmp/my-extra-files
```
Compatible with current:
```
spec:
  application:
      extraFiles:
      mountPath: /tmp
      configMaps:
        - name: 
          directory:  my-extra-files
```

In both cases Operator should generate MountVolume with MountPath = /tmp/my-extra-files, w/o SubPath
