### ISSUE TITLE
Update CRD with initial set of meaningful parameters

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#26]
/kind task

Follow-up to https://github.com/janus-idp/operator/issues/21#issuecomment-1834055506, where we reviewed and agreed upon a set of minimal viable parameters that could be included into the CRD.

This issue is about exposing and handling those parameters:

```yaml
spec:
  skipLocalDb: false
  application:
    appConfig:
      # All ConfigMaps will be mounted in the same place
      mountPath: "/opt/app-root/src"
      configMaps:
          - name: "my-app-config-cm12"
            # key is optional. All files will be mounted if not set. Otherwise, only the specified key will be mounted.
            key: "my-file1"
    extraFiles:
      # All ConfigMaps and Secrets will be mounted in the same place
      mountPath: /opt/app-root/src/path/to/my-extra-files
      configMaps:
          - name: "my-extra-config-secret12"
            # key is optional. All files will be mounted if not set.  Otherwise, only the specified key will be mounted.
            key: "my-file1"
      secrets:
          - name: "my-extra-config-secret12"
            # key is optional. All files will be mounted if not set.  Otherwise, only the specified key will be mounted.
            key: "my-file1"    
    # CM must have a key named 'dynamic-plugins.yaml'
    dynamicPluginsConfigMapName: "my-dynamic-plugins-config-cm"

    backendAuthSecret:
        name: "my-backend-auth-secret"
        # optional key in secret. Default value is "backend-secret"
        key: "my-auth-key"

    extraEnvs:
      configMaps:
        - name: "cm-name"
          # key is optional. Env vars from all keys if key is not set
          key: "key"
      secrets:
        - name: "secret-name"
          # key is optional. Env vars from all keys if key is not set
          key: "key"
      envs:
        - name: MY_ENV_VAR_1
          value: my-value-1
    replicas: 2
    image: "quay.io/rhdh/rhdh-hub-rhel9:1.0-194"
    imagePullSecrets:
      - rhdh-pull-secret
```

---

<details>
<summary>Previous version</summary>

```yaml
spec:
  backstage:

    appConfig:
      # optional 
      mountPath:  /opt/app-root/src
      - configMapRef:
          # all keys in the my-configmap configmap will be mounted to /opt/app-root/src/<key>
          name: my-appconfig
      - secretRef:
          name: my-secret-config

    extraConfig:
      # optional 
     mountPath: /opt/app-root/src
      - configMapRef:
          name: my-extra-configmap
      - secretRef:
          name: my-extra-secret

    env:
      - name: MY_ENV_VAR
        value: my-value
    envFrom:
      - configMapRef:
          name: my-configmap
      - secretRef:
          name: my-secret

    replicas: 1

    # image and imagePullSecret should apply to all containers (main and init)
    image: example.com/my-image:latest
    imagePullSecret: my-image-pull-secret

# Postponed
#    annotations:
#      # do not override default annotations
 #     my-annotation: my-value
#    labels:
 #     # do not override default labels
  #    my-label: my-value

# Postponed
#    command: ["node", "packages/backend"]
 #   args: ["--config /config/config.yaml"]
 

# Ingress Postponed for now
#   ingress:
#      enabled: true
 #     className: nginx
  #    annotations:
   #     kubernetes.io/ingress.class: nginx
 #     host: my-app.example.com
 #     path: /
 #     tls:
  #      enabled: true
   #     secretName: my-app-tls

# Priority - only allow modifying host and tls config
    route:
      enabled: true
      annotations:
        haproxy.router.openshift.io/timeout: 5m
      path: /
      tls:
        enabled: true
        caCertificate: 
        certificate:
        destinationCACertificate:
        key:
        insecureEdgeTerminationPolicy: redirect
        termination: edge

# Postponed
 #   service:
  #    type: ClusterIP
 #     annotations:
 #       service.beta.kubernetes.io/aws-load-balancer-type: external
 #     loadBalancerIP: 192.0.2.127
 #     clusterIP: 10.0.171.239

# Not needed, but we should be able to disable it
  postgresql:
    # if set to false will not create a postgresql database and user is expected to provide one
    # default is true
    enabled: true
    # TODO
```

</details>
