### ISSUE TITLE
Add labels and annotations recommended for OpenShift/Kubernetes applications to all resources created by the Operator

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#32]
This is a recommendation to increase interoperability with other tools working with K8s objects.
For example, it can help group a Backstage-managed instance in the OpenShift Topology Viewer, and make it easier to visualize a Backstage-managed application.
See https://github.com/redhat-developer/app-labels/blob/master/labels-annotation-for-openshift.adoc and https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels for more details.

---
This is a follow-up to a review comment on #29, which added some of those labels.

Would it make sense to have all these common labels applied on every sub-resource, like Pods as well? Not only on the parent Deployment?
This seems to be recommended in https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels.
I can only see the `backstage.io/app` label on the Backstage and DB Pods.
```yaml
[...]
spec:
  [...]
  selector:
    matchLabels:
      backstage.io/app: backstage-bs1
  template:
    metadata:
      creationTimestamp: null
      labels:
        backstage.io/app: backstage-bs1
```

_Originally posted by @rm3l in https://github.com/janus-idp/operator/pull/29#discussion_r1400305371_
