### ISSUE TITLE
Potential breaking change between 1.1.x and main (1.2) for the default Route URL naming pattern

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#355]
/kind bug

## What versions of software are you using?

- Operator version: latest commit on main: c889b0e52bca79a7d5dfd5424165b735dc5103b7

- OpenShift Local:
```
CRC version: 2.35.0+3956e8
OpenShift version: 4.15.10
Podman version: 4.4.4
```

## How did you run the operator exactly?

1. Started a fresh CRC cluster (no previous Backstage applications)
2. Took an existing CR with an app-config ConfigMap that was known to be working with 1.1:

<details>
<summary>Details</summary>

```yaml
apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: my-rhdh
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
data:
  "app-config-rhdh-app.yaml": |
    app:
      baseUrl: https://backstage-my-rhdh-my-ns.apps-crc.testing

  "app-config-rhdh-backend.yaml": |
    backend:
      baseUrl: https://backstage-my-rhdh-my-ns.apps-crc.testing
      csp:
        connect-src:
          - "'self'"
          - 'http:'
          - 'https:'
      cors:
        origin: https://backstage-my-rhdh-my-ns.apps-crc.testing
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      auth:
        dangerouslyDisableDefaultAuthPolicy: true
        keys:
          - secret: "xxx"
```

</details>

3. Started the operator from the main branch and deploy the manifest above
5. Wait until the Backstage application pod is ready.

## Actual behavior

The documentation in 1.1 depicts the URL naming format (used for `backend.baseUrl`, `app.baseUrl` and `backend.cors.origin`) as: `https://backstage-<CUSTOM_RESOURCE_NAME>-<NAMESPACE_NAME>.<OPENSHIFT_INGRESS_DOMAIN>`.
But if we look at the Route created by the operator on main, it now has the following naming format: `https://<CUSTOM_RESOURCE_NAME>-backstage-<NAMESPACE_NAME>.<OPENSHIFT_INGRESS_DOMAIN>`

## Expected behavior

Changing the URL format will break users' configurations, as they will need to change them manually to make it work properly with the Route created by the Operator.

As discussed during the previous working group call, we decided to revert to the previous URL format on 1.1, to make sure not to introduce breaking changes. No doc change will therefore be required.
