### ISSUE TITLE
Investigate the reason why PostgreSQL PV is not deleted with Backstage CR

### ISSUE THREAD

**Issue by gazarenkov** [janus-idp/operator#43]
The way to reproduce:
- Make run operator with local Postgre and  "own-runtime = true" parameter 
- Create (default) Backstage CR (bs1 for example)
- Make sure all deployed correctly, check PV object, it must contain something like:
```
ownerReferences:                                                                                                                                                                                                
    - apiVersion: backstage.io/v1alpha1                                                                                                                                                                             
       blockOwnerDeletion: true                                                                                                                                                                                      
       controller: true                                                                                                                                                                                              
       kind: Backstage                                                                                                                                                                                               
       name: bs1   
```                                                                                                                                                                                                 

- Delete CR
Expected result: all associated runtime objects are deleted
Observed: PV is not deleted even if contain correct ownerReferences.
