### ISSUE TITLE
Make it possible to inject user-provided environment variables into the Backstage Deployment

### ISSUE THREAD

**Issue by rm3l** [janus-idp/operator#52]
In https://github.com/janus-idp/operator/pull/27, we added support for user-defined app-configs and dynamic plugins config, backed by either ConfigMaps or Secrets.

As discussed in https://github.com/janus-idp/operator/pull/27#discussion_r1409033131, the common and recommended approach for most app-config files would be files referencing environment variables backed by Secrets, [like so](https://backstage.io/docs/auth/github/provider#configuration):

```yaml
auth:
  environment: prod
  providers:
    github:
      prod:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}
```

One possible approach, depicted in the [upstream Backstage deployment guide on Kubernetes](https://backstage.io/docs/deployment/k8s/#creating-the-backstage-instance), could be to reference a `backstage-secrets` secret, just like what we are doing with the DB credentials. Here, this secret would need to be optional.

```yaml
envFrom:
  - secretRef:
      name: postgres-secrets
  - secretRef:
      name: backstage-secrets
      optional: true
```

This would not require adding specific fields to the CRD.
